name             'learn_chef_iis'
maintainer       'Jordy de Muijnk'
maintainer_email 'jordydemuijnk@ziggo.nl'
license          'Apache 2.0'
description      'Installs and configures IIS, the W3SVC, and sets a basic Roel Bindels home page.'
long_description 'Installs and configures IIS, the W3SVC, and sets a basic home page. This cookbook is used by the Learn Chef tutorials. http://learn.getchef.com'
supports         'windows'
version          '0.1.2'
